require 'rails_helper'

RSpec.describe ApplicationHelper, type: :helper do
  skip '#apple_touch_icon_link_tags'
  skip '#a_reply?'
  skip '#blank'
  skip '#editing?'
  skip '#hide?'
  skip '#in_a_list?'
  skip '#license'
  skip '#license_name_and_url'
  skip '#license_years_range'
  skip '#on_permalink?'
  skip '#page_description'
  skip '#show?'
  skip '#show_action?'
  skip '#show_nav_to?'
  skip '#show_site_nav?'
  skip '#site_title'
  skip '#writing?'
end
