require "rails_helper"

RSpec.describe ApplicationHelper, type: :helper do
  # pending "#apple_touch_icon_link_tags"
  # pending "#a_reply?"
  # pending "#blank"
  # pending "#editing?"
  # pending "#hide?"
  # pending "#in_a_list?"
  # pending "#license"
  # pending "#license_name_and_url"
  # pending "#license_years_range"
  # pending "#on_permalink?"
  # pending "#page_description"
  # pending "#show?"
  # pending "#show_action?"
  # pending "#show_nav_to?"
  # pending "#show_site_nav?"
  # pending "#site_title"
  # pending "#writing?"
end
